### ISSUE TITLE
tag/0.0.1: segment fault

### ISSUE THREAD

**Issue by ChunyuLiao** [plctlab/gollvm#8]
Latest code:​ https://github.com/realqhc/gollvm/tree/gollvm-build-riscv

Download : llvm-goc bin:https://github.com/realqhc/gollvm/releases/tag/0.0.1

cat hello.go 
package main
import "fmt"
func main() {
            fmt.Println("hello world")
}

llvm-goc -static-libgo -latomic hello.go 
$ ./a.out
Segmentation fault (core dumped)

gdb a.out 
GNU gdb (Ubuntu 10.1-2ubuntu2) 10.1.90.20210411-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "riscv64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from a.out...
(gdb) r
Starting program: /home/liaochunyu/a.out 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/riscv64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
runtime.argv_index (argv=0x30000000003, i=-2967) at /home/anakano/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/runtime1.go:69
69      /home/anakano/llvm-project/llvm/tools/gollvm/gofrontend/libgo/go/runtime/runtime1.go: No such file or directory.
(gdb)

**Comment by melonedo** [comment]
This is because LLVM did not handle static chain parameters on RISC-V.
Fixed by https://github.com/melonedo/llvm-project/commit/7ff70876acad5a96bdd056fd8253bde15120a522.

**Comment by ChunyuLiao** [comment]
fixed. @melonedo Thanks.

$ llvm-goc -static-libgo -latomic hello.go -o hello
$ ./hello 
hello world
